import { describe,expect,it } from "vitest";
import { LocalCoachService, localIllegalMessage } from "@/lib/coach/local-coach-service";
import { explainOpponentMove } from "@/lib/coach/position-explanation";
import { moveSentence } from "@/lib/conversation/message-builders";
import type { CoachRequest, SupportedLocale } from "@/lib/types";

function request(locale:SupportedLocale):CoachRequest{return{locale,gameId:"game",turnId:"turn",player:{nickname:"A",level:"absolute_beginner",learnedRules:[],recurringMistakes:[]},game:{fenBeforeUserMove:"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",fenAfterUserMove:"rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",pgn:"1. e4",turnNumber:1,status:"playing"},userMove:{san:"e4",from:"e2",to:"e4",piece:"pawn"},legalMovesBeforeUserMove:["e4"],legalMovesAfterOpponentMove:["Nf3"],requestedDetail:"default"};}
describe("LocalCoachService",()=>{
  it.each(["zh-CN","en","ja"] as SupportedLocale[])("returns localized output for %s",async(locale)=>{const result=await new LocalCoachService().explainTurn(request(locale));expect(result.locale).toBe(locale);expect(result.userMoveSummary.length).toBeGreaterThan(5);expect(result.provider).toBe("local_fallback");});
  it("expands SAN notation for a complete beginner",async()=>{const input=request("zh-CN");input.opponentMove={san:"Nf6",from:"g8",to:"f6",piece:"knight"};const result=await new LocalCoachService().explainTurn(input);expect(result.opponentMoveExplanation).toContain("Nf6（马从 g8 走到 f6）");});
  it("explains queenside castling with check as one special move",async()=>{const input=request("zh-CN");input.opponentMove={san:"O-O-O+",from:"e8",to:"c8",piece:"king"};const result=await new LocalCoachService().explainTurn(input);expect(result.opponentMoveExplanation).toContain("王从 e8 到 c8，车同时从 a8 到 d8");expect(result.opponentMoveExplanation).toContain("+ 表示这一步还形成了将军");expect(result.ruleTaught?.key).toBe("castling");});
  it("describes the concrete line opened by d6 instead of returning the old generic template",()=>{const result=explainOpponentMove("zh-CN","rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1","rnbqkbnr/ppp1pppp/3p4/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",{san:"d6",from:"d7",to:"d6",piece:"pawn"});expect(result.explanation).toContain("打开了象的活动路线");expect(result.explanation).not.toContain("发展棋子、争夺空间");});
  it("expands an engine recommendation into SAN plus beginner-friendly coordinates",async()=>{const input=request("zh-CN");input.requestedDetail="hint_3";input.legalMovesAfterOpponentMove=["Na3","Nc3"];input.recommendedMove={san:"Na3",from:"b1",to:"a3",piece:"knight"};const result=await new LocalCoachService().explainTurn(input);expect(result.nextObservation).toContain("推荐走法：Na3（马从 b1 走到 a3）");expect(result.nextObservation).toContain("本地棋力引擎");});
  it("describes captures as movement followed by the captured piece",()=>{expect(moveSentence("zh-CN","player",{san:"exd5",from:"e4",to:"d5",piece:"pawn",captured:"pawn"})).toBe("你把兵从 e4 走到 d5（exd5），并吃掉了对手的兵。");expect(moveSentence("zh-CN","opponent",{san:"Qxd5",from:"d8",to:"d5",piece:"queen",captured:"pawn"})).toBe("对手把后从 d8 走到 d5（Qxd5），并吃掉了你的兵。");});
  it("explains an illegal sideways pawn in every language",()=>{expect(localIllegalMessage("zh-CN","pawn")).toContain("横");expect(localIllegalMessage("en","pawn")).toContain("sideways");expect(localIllegalMessage("ja","pawn")).toContain("横");});
});
