"use client";
import {useEffect,useRef,useState} from "react";
import type {CoachMode,ConversationMessage,EngineAnalysisSnapshot,PlayerProfile,RequestedDetail} from "@/lib/types";
import type {Messages} from "@/lib/i18n/messages";
import {Avatar} from "@/components/Avatar";

export function ConversationPanel({messages,items,thinking,canAsk,analysis,coachMode,profile,onCoachMode,onAsk}:{messages:Messages;items:ConversationMessage[];thinking:boolean;canAsk:boolean;analysis:EngineAnalysisSnapshot|null;coachMode:CoachMode;profile:PlayerProfile;onCoachMode:(mode:CoachMode)=>void;onAsk:(detail:RequestedDetail)=>void}){
  const bodyRef=useRef<HTMLDivElement>(null);const [details,setDetails]=useState(false);
  useEffect(()=>{const body=bodyRef.current;if(!body)return;const frame=requestAnimationFrame(()=>body.scrollTo({top:body.scrollHeight,behavior:"smooth"}));return()=>cancelAnimationFrame(frame);},[items]);
  const roles={player:messages.conversation.me,opponent:messages.conversation.opponent,coach:messages.conversation.coach,system:messages.conversation.system};
  return <aside className="coach-card conversation-card" aria-label={messages.conversation.title}><div className="coach-head"><div className="coach-title"><span>♞</span>{messages.conversation.title}</div><label className="coach-mode"><span>{messages.conversation.coachMode}</span><select value={coachMode} onChange={event=>onCoachMode(event.target.value as CoachMode)}><option value="local">{messages.conversation.localCoach}</option><option value="disabled">{messages.conversation.coachOff}</option></select></label></div>
    <div className="conversation-body" ref={bodyRef}>{items.length===0?<div className="coach-empty"><div className="coach-empty-icon">♞</div>{messages.conversation.empty}</div>:items.map(item=><article className={`conversation-message role-${item.role}`} key={item.id} data-message-type={item.type}><header>{item.role==="system"?<span className="conversation-avatar">•</span>:<Avatar kind={item.role} profile={item.role==="player"?profile:undefined}/>}<strong>{roles[item.role]}</strong>{item.status==="streaming"&&<span className="thinking-dots" aria-label={messages.conversation.analyzing}><i/><i/><i/></span>}</header><p>{item.text}</p>{item.engineAnalysis&&details&&<EngineDetails messages={messages} analysis={item.engineAnalysis}/>}</article>)}</div>
    {analysis&&<button className="engine-details-toggle" onClick={()=>setDetails(value=>!value)}>{details?messages.conversation.hideDetails:messages.conversation.showDetails}</button>}
    <div className="conversation-actions"><button className="primary" disabled={thinking||!canAsk||coachMode==="disabled"} onClick={()=>onAsk("hint_1")}>{messages.conversation.whatShouldIDo}</button><button className="secondary" disabled={thinking||!canAsk||coachMode==="disabled"} onClick={()=>onAsk("hint_2")}>{messages.coach.hint2}</button><button className="secondary" disabled={thinking||!canAsk||coachMode==="disabled"} onClick={()=>onAsk("hint_3")}>{messages.coach.hint3}</button></div>
    <div className="progress-card"><div className="progress-row">{[[profile.lessonProgress.learnedRules.length,messages.progress.rules],[profile.lessonProgress.gamesPlayed,messages.progress.games],[profile.lessonProgress.legalMovesMade,messages.progress.moves],[profile.lessonProgress.illegalMoveAttempts,messages.progress.mistakes]].map(([value,label])=><div key={String(label)}><div className="progress-value">{value}</div><div className="progress-label">{label}</div></div>)}</div></div>
  </aside>;
}
function EngineDetails({messages,analysis}:{messages:Messages;analysis:EngineAnalysisSnapshot}){const score=analysis.candidates[0]?.score;const scoreText=!score?"—":score.type==="centipawn"?`${score.value>=0?"+":""}${(score.value/100).toFixed(2)}`:`M${score.value}`;return <div className="engine-analysis-details"><div><b>{messages.conversation.depth}:</b> {analysis.depth}</div><div><b>{messages.conversation.score}:</b> {scoreText}</div><div><b>{messages.conversation.mainLine}:</b> {analysis.candidates[0]?.principalVariationSan?.join(" ")||analysis.candidates[0]?.principalVariationUci.join(" ")||"—"}</div></div>}
